### ISSUE TITLE
Geohash precision

### ISSUE THREAD

**Issue by sibartlett** [mattjohnsonpint/GeoTimeZone#10]
The current implementation uses geohashes that are 5 characters in length. This gives a worst case precision of ~4.9km.

This imprecision mostly affects us where two or more time zones meet each other. There are cases where a geohash intersects with multiple timezones, and we currently just pick one time zone and discard the others.

I propose we either do one of the following:
1. Record all matches in the index. When a search matches multiple geohashes, we provide the caller all possible matches. The result object could have two properties:
   SuccessfulMatch and PossibleMatches.
2. We continue as is, but we introduce a byte per line that signals how accurate the result is.

I prefer the first option, but would appreciate your thoughts.

**Comment by songjiahong** [comment]
Thanks your guys for this cool tool. I have a idea for a more precision result, we don't need to change a lot for current implementation. The extra steps are:
- In the timezone name file (TZ.dat), record the timezone polygon file position in the shape file
- When multiple timezone founded for given latitude & longitude, iterate the polygons for each timezone and check whether the location falls in

For this change, we can find out the exact one to match the location. What's your thoughts?

**Comment by mj1856** [comment]
We'd also have to include the polygon data.  Part of the benefit of indexing is that the index is much smaller than the original shapefile.

**Comment by songjiahong** [comment]
If we include the polygon data in the index file, would the file size be very close as the original shapefile?

**Comment by mattjohnsonpint** [comment]
Closing this, as I'll likely never get to it.

**Comment by mattjohnsonpint** [comment]
For anyone that is interested, please provide feedback on the precision issue here: #56

Thanks!
