### ISSUE TITLE
Bullhead City, AZ incorrectly identified as PST

### ISSUE THREAD

**Issue by lanegoolsby** [mattjohnsonpint/GeoTimeZone#47]
Originally reported here: https://github.com/evansiroky/timezone-boundary-builder/issues/103

The lat and long for Bullhead City, AZ is being identified as Pacific Time Zone. It should be MST. I do see an alternative result that is MST, but that should be the primary result, not the secondary, correct?

[OpenMap](https://www.openstreetmap.org/relation/6695742) shows the correct state info and the [Wikidata link on that page](https://www.wikidata.org/wiki/Q79432) shows the correct timezone info. 

Example coordinates. 
35.0959f, -114.598f
35.115556f, -114.588611f

![image](https://user-images.githubusercontent.com/10758510/122102021-d32d1600-cdc9-11eb-9b96-7e3827237a9b.png)

**Comment by mattjohnsonpint** [comment]
This is another case of the geohash index precision issue described in #10 in the early development of this library.  See also the myriad of other issues referenced in that one.

I'm going to close this particular issue as it's an example of a larger problem, but will revisit the ideas in #10.  I have a few new tricks to try as well.

Thanks for reporting.

**Comment by mattjohnsonpint** [comment]
Please provide feedback on the precision issue here: #56
Thanks!
