### ISSUE TITLE
The type 'System.Object' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by derekdinan** [mattjohnsonpint/GeoTimeZone#49]
I added a reference to the `GeoTimeZone.dll` file which I extracted from the Nuget package [like so](https://gist.github.com/fex80/976ff887acb825171de6). 

The only line of code I am using the library for is this:  `string timezone = TimeZoneLookup.GetTimeZone(latitude, longitude).Result;`

But I keep getting an error when compiling: `Error #CS0012 on line 86 - The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
(09:26:01) Compilation error. See logs/errors/compiler.log for more information.`

I have also referenced `netstandard.dll` using the same method of NuGet extraction yet the issue still persists.

**Comment by mattjohnsonpint** [comment]
Why are you manually extracting a DLL from the package?  You should just reference the nuget package in your csproj.

```
dotnet add package GeoTimeZone
```

Note that the package contains different versions of the DLL depending on the build target.  Which version of .NET are you targeting?
