### ISSUE TITLE
East India misdetection

### ISSUE THREAD

**Issue by benberlin7** [mattjohnsonpint/GeoTimeZone#54]
https://www.timeanddate.com/time/zone/india/agartala
Lat : 23.88
Lon : 91.25

Detects Timezone : Asia/Dhaka UTC+6 (and wrong country Bangladesh)
Should be : India Standard Time UTC+5,5

Keep up the good work!

**Comment by mattjohnsonpint** [comment]
This is a geohash precision issue (see #10).

The location given is very close to the border with Bangladesh.
https://www.openstreetmap.org/?mlat=23.88&mlon=91.25&zoom=12#map=12/23.88/91.25

However, you will indeed see `Asia/Kolkata` in the `AlternativeResults` array.

The city center (as listed on Wikipedia) returns the correct results
https://www.openstreetmap.org/?mlat=23.833333&mlon=91.283333&zoom=12#map=12/23.8333/91.2833

**Comment by mattjohnsonpint** [comment]
@benberlin7 - Please provide feedback on the precision issue here: #56

Thanks!
