### ISSUE TITLE
Russian island misdetection?

### ISSUE THREAD

**Issue by benberlin7** [mattjohnsonpint/GeoTimeZone#55]
Preodrasheniyai
Lat : 74.667
Lon: 112.5
https://www.google.com/maps/place/74%C2%B040'01.2%22N+112%C2%B030'00.0%22E/@74.6221272,114.7780538,6.19z/data=!4m4!3m3!8m2!3d74.667!4d112.5

Detects : UTC+7 Asia/Krasnoyarsk
Should be (???) : UTC+9 ? https://www.timeanddate.com/time/zone/@74.667,112.5
Near spot"Nordwik" has UTC+7 https://www.timeanddate.com/time/zone/@2021666 
So I'm not sure what is correct here.

Keep up the good work!

**Comment by mattjohnsonpint** [comment]
Like in #54, this is probably a precision issue.  The spot you've selected isn't on the island at all, but in the waters near the border.

https://www.openstreetmap.org/?mlat=74.667&mlon=112.5&zoom=12#map=8/74.457/112.994

**Comment by mattjohnsonpint** [comment]
Also keep in mind that all of the map data comes from https://github.com/evansiroky/timezone-boundary-builder

If you think there's something wrong with the map, I encourage you to examine the data and submit the concern there.  Thanks.
