### ISSUE TITLE
Arizona timezones incorrect

### ISSUE THREAD

**Issue by centurijon** [mattjohnsonpint/GeoTimeZone#58]
When calling TimeZoneLookup.GetTimeZone(latitude, longitude), locations in Arizona are being returned as America/Los_Angeles instead of America/Phoenix

samples:
35.109183, -114.598155 zip code 86442
35.103325, -114.597998 zip code 86442
35.108012, -114.610273 zip code 86442
32.698297, -114.581565 zip code 85365
35.082686, -114.596978 zip code 86442
35.088242, -114.598138 zip code 86442
34.503053, -114.350817 zip code 86403
32.698399, -114.623759 zip code 85364

**Comment by mattjohnsonpint** [comment]
Hi.  This is likely another precision issue, as these locations are near the border.  See #10.

Also, please chime in on #56 where we are discussing options for improving precision.  THanks.
