### ISSUE TITLE
error in determining tz by coordinates

### ISSUE THREAD

**Issue by zabavin** [mattjohnsonpint/GeoTimeZone#60]
for example
           point         bad                   good
POINT (98.312637 24.100513)	Asia/Shanghai	Asia/Yangon
POINT (-97.507195 25.846584)	America/Chicago	America/Matamoros
POINT (-100.966927 29.328777)	America/Chicago	America/Matamoros
POINT (-62.982861 -40.824215)	America/Argentina/Buenos_Aires	America/Argentina/Salta
POINT (-71.703903 19.550138)	America/Port-au-Prince	America/Santo_Domingo
POINT (-59.796837 3.380263)	America/Boa_Vista	America/Guyana
POINT (-47.462345 -7.333665)	America/Araguaina	America/Fortaleza
POINT (-48.562874 -6.392829)	America/Araguaina	America/Belem
POINT (-38.000431 -11.184197)	America/Bahia	America/Maceio
POINT (66.071091 54.43792)	Asia/Almaty	Asia/Qostanay
POINT (28.277309 45.454208)	Europe/Bucharest	Europe/Kyiv
POINT (23.570456 48.016441)	Europe/Bucharest	Europe/Kyiv
POINT (17.412973 -28.362768)	Africa/Johannesburg	Africa/Windhoek
POINT (30.416668 -15.616667)	Africa/Harare	Africa/Maputo
POINT (-52.334019 3.166003)	America/Belem	America/Cayenne
POINT (-51.801823 3.890881)	America/Belem	America/Cayenne
POINT (-47.441559 -6.558501)	America/Araguaina	America/Fortaleza
POINT (-47.529423 -4.455852)	America/Belem	America/Fortaleza
POINT (-38.17741 -10.713698)	America/Bahia	America/Maceio
POINT (-47.397381 -6.344639)	America/Araguaina	America/Fortaleza
POINT (27.796194 48.448013)	Europe/Chisinau	Europe/Kyiv
POINT (52.253399 53.7281)	Asia/Yekaterinburg	Europe/Samara
POINT (45.568398 50.543941)	Europe/Saratov	Europe/Volgograd
POINT (49.7775 53.904999)	Europe/Samara	Europe/Ulyanovsk
POINT (145.603546 63.837921)	Asia/Magadan	Asia/Ust-Nera
POINT (47.6278 50.483898)	Asia/Oral	Europe/Saratov

**Comment by mattjohnsonpint** [comment]
These are related to the precision issues previously described in #10 and many others, and currently being discussed in #56.  Please see proposals there and add feedback if you have any.  Thanks.
